USE [master]
GO

/****** Object:  Database [task]    Script Date: 21-02-2022 18:33:03 ******/
CREATE DATABASE [task]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'task', FILENAME = N'C:\Users\Ranjith\task.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'task_log', FILENAME = N'C:\Users\Ranjith\task_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [task].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [task] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [task] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [task] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [task] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [task] SET ARITHABORT OFF 
GO

ALTER DATABASE [task] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [task] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [task] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [task] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [task] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [task] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [task] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [task] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [task] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [task] SET  ENABLE_BROKER 
GO

ALTER DATABASE [task] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [task] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [task] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [task] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [task] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [task] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [task] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [task] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [task] SET  MULTI_USER 
GO

ALTER DATABASE [task] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [task] SET DB_CHAINING OFF 
GO

ALTER DATABASE [task] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [task] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [task] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [task] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [task] SET QUERY_STORE = OFF
GO

ALTER DATABASE [task] SET  READ_WRITE 
GO


